BBLDN\EntityExistsValidatorBundle\Doctrine\Validator\EntityExistsValidator:
    arguments:
        - '@Doctrine\Persistence\ManagerRegistry'

BBLDN\EntityExistsValidatorBundle\Doctrine\Validator\EntityExistsByFieldValidator:
    arguments:
        - '@Doctrine\Persistence\ManagerRegistry'
