services:
    BBLDN\EntityExistsValidatorBundle\Doctrine\Validator\EntityExistsValidator:
        tags: ['validator.constraint_validator']
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
    
    BBLDN\EntityExistsValidatorBundle\Doctrine\Validator\EntityExistsByFieldValidator:
        tags: ['validator.constraint_validator']
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
